import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'


  function handlepaste(e: React.ClipboardEvent) {
    // // Browsers that support the 'text/html' type in the Clipboard API (Chrome, Firefox 22+)
    if (e && e.clipboardData && e.clipboardData.types && e.clipboardData.getData) {
      let types = e.clipboardData.types;
      if (((types instanceof DOMStringList) && types.contains("text/html")) || (types.indexOf && types.indexOf('text/html') !== -1)) {
        let pastedData = e.clipboardData.getData('text/plain');
        processPaste(pastedData);
        // // Stop the data from actually being pasted
        e.stopPropagation();
        e.preventDefault();
        return false;
      }
    }
  }

  function processPaste(pastedData: String) {
    // console.log( pastedData);
    alert(pastedData);
  }


const Home: NextPage = () => {
  const [clipboardItens, setClipboardItens] = useState([]);

  return (
    <div id="editableDiv" className={styles.container} onPaste={handlepaste}>
      <Head>
        <title>Bookmark Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bookmarks
        </h1>

        <div className={styles.grid}>
          <>
          {clipboardItens.length > 0 && clipboardItens.map((item: JSX.Element) => {
            console.log(item)
          })}
          </>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/lumamontes"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Luma
         
        </a>
      </footer>
    </div>
  )
}

export default Home
